name: Wheat
description: 'A simple Jekyll starter-template for designers.'

markdown: kramdown

pygments: true

include:
- .htaccess

exclude:
- README.md
- Rakefile
- _site
- .sass-cache

keep_files:
- .git

permalink: /writing/:title
