name: Wheat
description: 'a Jekyll starter-template for designers.'
author: Pedro Carmo

markdown: kramdown

pygments: true

include:
- .htaccess

exclude:
- README.md
- Rakefile
- _site
- .sass-cache

keep_files:
- .git
